# Generated by Django 6.0.5 on 2026-05-14 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoshop', '0005_remove_register_password_register_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photoshop.category'),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
