# Generated by Django 6.0.5 on 2026-05-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoshop', '0006_alter_photo_category_alter_register_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='password',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
