# Generated by Django 6.0.5 on 2026-05-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoshop', '0007_register_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='register',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
