# Generated by Django 6.0.5 on 2026-05-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photoshop', '0010_remove_gallery_image_gallery_title_galleryimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='title',
        ),
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default='', upload_to='gallery/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
